# DO NOT ACTUALLY USE THIS FOR PRODUCTIONS
services:
  web:
    container_name: kigwiki-site
    build: .
    ports:
      - "3100:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run start -- --host 0.0.0.0
    stdin_open: true # for interactive shell
    tty: true # for interactive shell 